language: python
os: linux
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.9"
# command to install dependencies
install:
  - pip install -r prequirements.txt
  - pip install .
# command to run tests
script:
  - flake8 ./